# Generated by Django 4.2.22 on 2025-06-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('unit', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
