# Generated by Django 4.2.22 on 2025-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_membermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_images/'),
        ),
    ]
