# Generated by Django 4.2.22 on 2025-06-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_membermessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
